package com.fair.tool_belt_abv.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val stmd_theme_light_primary = Color(0xFF974812)
val stmd_theme_light_onPrimary = Color(0xFFFFFFFF)
val stmd_theme_light_primaryContainer = Color(0xFFFFDBCA)
val stmd_theme_light_onPrimaryContainer = Color(0xFF331200)
val stmd_theme_light_secondary = Color(0xFF765848)
val stmd_theme_light_onSecondary = Color(0xFFFFFFFF)
val stmd_theme_light_secondaryContainer = Color(0xFFFFDBCA)
val stmd_theme_light_onSecondaryContainer = Color(0xFF2B160A)
val stmd_theme_light_tertiary = Color(0xFF636032)
val stmd_theme_light_onTertiary = Color(0xFFFFFFFF)
val stmd_theme_light_tertiaryContainer = Color(0xFFEAE5AB)
val stmd_theme_light_onTertiaryContainer = Color(0xFF1E1C00)
val stmd_theme_light_error = Color(0xFFBA1A1A)
val stmd_theme_light_errorContainer = Color(0xFFFFDAD6)
val stmd_theme_light_onError = Color(0xFFFFFFFF)
val stmd_theme_light_onErrorContainer = Color(0xFF410002)
val stmd_theme_light_background = Color(0xFFFFFBFF)
val stmd_theme_light_onBackground = Color(0xFF201A17)
val stmd_theme_light_surface = Color(0xFFFFFBFF)
val stmd_theme_light_onSurface = Color(0xFF201A17)
val stmd_theme_light_surfaceVariant = Color(0xFFF4DED4)
val stmd_theme_light_onSurfaceVariant = Color(0xFF52443D)
val stmd_theme_light_outline = Color(0xFF85746B)
val stmd_theme_light_inverseOnSurface = Color(0xFFFBEEE9)
val stmd_theme_light_inverseSurface = Color(0xFF362F2C)
val stmd_theme_light_inversePrimary = Color(0xFFFFB68F)
val stmd_theme_light_shadow = Color(0xFF000000)
val stmd_theme_light_surfaceTint = Color(0xFF974812)
val stmd_theme_light_outlineVariant = Color(0xFFD7C2B9)
val stmd_theme_light_scrim = Color(0xFF000000)

val stmd_theme_dark_primary = Color(0xFFFFB68F)
val stmd_theme_dark_onPrimary = Color(0xFF542100)
val stmd_theme_dark_primaryContainer = Color(0xFF773200)
val stmd_theme_dark_onPrimaryContainer = Color(0xFFFFDBCA)
val stmd_theme_dark_secondary = Color(0xFFE6BEAB)
val stmd_theme_dark_onSecondary = Color(0xFF432B1D)
val stmd_theme_dark_secondaryContainer = Color(0xFF5C4132)
val stmd_theme_dark_onSecondaryContainer = Color(0xFFFFDBCA)
val stmd_theme_dark_tertiary = Color(0xFFCEC991)
val stmd_theme_dark_onTertiary = Color(0xFF343208)
val stmd_theme_dark_tertiaryContainer = Color(0xFF4B481D)
val stmd_theme_dark_onTertiaryContainer = Color(0xFFEAE5AB)
val stmd_theme_dark_error = Color(0xFFFFB4AB)
val stmd_theme_dark_errorContainer = Color(0xFF93000A)
val stmd_theme_dark_onError = Color(0xFF690005)
val stmd_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val stmd_theme_dark_background = Color(0xFF201A17)
val stmd_theme_dark_onBackground = Color(0xFFECE0DB)
val stmd_theme_dark_surface = Color(0xFF201A17)
val stmd_theme_dark_onSurface = Color(0xFFECE0DB)
val stmd_theme_dark_surfaceVariant = Color(0xFF52443D)
val stmd_theme_dark_onSurfaceVariant = Color(0xFFD7C2B9)
val stmd_theme_dark_outline = Color(0xFF9F8D84)
val stmd_theme_dark_inverseOnSurface = Color(0xFF201A17)
val stmd_theme_dark_inverseSurface = Color(0xFFECE0DB)
val stmd_theme_dark_inversePrimary = Color(0xFF974812)
val stmd_theme_dark_shadow = Color(0xFF000000)
val stmd_theme_dark_surfaceTint = Color(0xFFFFB68F)
val stmd_theme_dark_outlineVariant = Color(0xFF52443D)
val stmd_theme_dark_scrim = Color(0xFF000000)

val StoutLightColors = lightColorScheme(
    primary = stmd_theme_light_primary,
    onPrimary = stmd_theme_light_onPrimary,
    primaryContainer = stmd_theme_light_primaryContainer,
    onPrimaryContainer = stmd_theme_light_onPrimaryContainer,
    secondary = stmd_theme_light_secondary,
    onSecondary = stmd_theme_light_onSecondary,
    secondaryContainer = stmd_theme_light_secondaryContainer,
    onSecondaryContainer = stmd_theme_light_onSecondaryContainer,
    tertiary = stmd_theme_light_tertiary,
    onTertiary = stmd_theme_light_onTertiary,
    tertiaryContainer = stmd_theme_light_tertiaryContainer,
    onTertiaryContainer = stmd_theme_light_onTertiaryContainer,
    error = stmd_theme_light_error,
    errorContainer = stmd_theme_light_errorContainer,
    onError = stmd_theme_light_onError,
    onErrorContainer = stmd_theme_light_onErrorContainer,
    background = stmd_theme_light_background,
    onBackground = stmd_theme_light_onBackground,
    surface = stmd_theme_light_surface,
    onSurface = stmd_theme_light_onSurface,
    surfaceVariant = stmd_theme_light_surfaceVariant,
    onSurfaceVariant = stmd_theme_light_onSurfaceVariant,
    outline = stmd_theme_light_outline,
    inverseOnSurface = stmd_theme_light_inverseOnSurface,
    inverseSurface = stmd_theme_light_inverseSurface,
    inversePrimary = stmd_theme_light_inversePrimary,
    surfaceTint = stmd_theme_light_surfaceTint,
    outlineVariant = stmd_theme_light_outlineVariant,
    scrim = stmd_theme_light_scrim,
)


val StoutDarkColors = darkColorScheme(
    primary = stmd_theme_dark_primary,
    onPrimary = stmd_theme_dark_onPrimary,
    primaryContainer = stmd_theme_dark_primaryContainer,
    onPrimaryContainer = stmd_theme_dark_onPrimaryContainer,
    secondary = stmd_theme_dark_secondary,
    onSecondary = stmd_theme_dark_onSecondary,
    secondaryContainer = stmd_theme_dark_secondaryContainer,
    onSecondaryContainer = stmd_theme_dark_onSecondaryContainer,
    tertiary = stmd_theme_dark_tertiary,
    onTertiary = stmd_theme_dark_onTertiary,
    tertiaryContainer = stmd_theme_dark_tertiaryContainer,
    onTertiaryContainer = stmd_theme_dark_onTertiaryContainer,
    error = stmd_theme_dark_error,
    errorContainer = stmd_theme_dark_errorContainer,
    onError = stmd_theme_dark_onError,
    onErrorContainer = stmd_theme_dark_onErrorContainer,
    background = stmd_theme_dark_background,
    onBackground = stmd_theme_dark_onBackground,
    surface = stmd_theme_dark_surface,
    onSurface = stmd_theme_dark_onSurface,
    surfaceVariant = stmd_theme_dark_surfaceVariant,
    onSurfaceVariant = stmd_theme_dark_onSurfaceVariant,
    outline = stmd_theme_dark_outline,
    inverseOnSurface = stmd_theme_dark_inverseOnSurface,
    inverseSurface = stmd_theme_dark_inverseSurface,
    inversePrimary = stmd_theme_dark_inversePrimary,
    surfaceTint = stmd_theme_dark_surfaceTint,
    outlineVariant = stmd_theme_dark_outlineVariant,
    scrim = stmd_theme_dark_scrim,
)
