package com.fair.tool_belt_abv.ui.theme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val hops_theme_light_primary = Color(0xFF226C2D)
val hops_theme_light_onPrimary = Color(0xFFFFFFFF)
val hops_theme_light_primaryContainer = Color(0xFFA7F5A6)
val hops_theme_light_onPrimaryContainer = Color(0xFF002105)
val hops_theme_light_secondary = Color(0xFF52634F)
val hops_theme_light_onSecondary = Color(0xFFFFFFFF)
val hops_theme_light_secondaryContainer = Color(0xFFD5E8CF)
val hops_theme_light_onSecondaryContainer = Color(0xFF101F10)
val hops_theme_light_tertiary = Color(0xFF39656B)
val hops_theme_light_onTertiary = Color(0xFFFFFFFF)
val hops_theme_light_tertiaryContainer = Color(0xFFBCEBF1)
val hops_theme_light_onTertiaryContainer = Color(0xFF001F23)
val hops_theme_light_error = Color(0xFFBA1A1A)
val hops_theme_light_errorContainer = Color(0xFFFFDAD6)
val hops_theme_light_onError = Color(0xFFFFFFFF)
val hops_theme_light_onErrorContainer = Color(0xFF410002)
val hops_theme_light_background = Color(0xFFFCFDF7)
val hops_theme_light_onBackground = Color(0xFF1A1C19)
val hops_theme_light_surface = Color(0xFFFCFDF7)
val hops_theme_light_onSurface = Color(0xFF1A1C19)
val hops_theme_light_surfaceVariant = Color(0xFFDEE5D9)
val hops_theme_light_onSurfaceVariant = Color(0xFF424940)
val hops_theme_light_outline = Color(0xFF72796F)
val hops_theme_light_inverseOnSurface = Color(0xFFF0F1EB)
val hops_theme_light_inverseSurface = Color(0xFF2F312D)
val hops_theme_light_inversePrimary = Color(0xFF8CD88C)
val hops_theme_light_shadow = Color(0xFF000000)
val hops_theme_light_surfaceTint = Color(0xFF226C2D)
val hops_theme_light_outlineVariant = Color(0xFFC2C9BD)
val hops_theme_light_scrim = Color(0xFF000000)

val hops_theme_dark_primary = Color(0xFF8CD88C)
val hops_theme_dark_onPrimary = Color(0xFF00390E)
val hops_theme_dark_primaryContainer = Color(0xFF005318)
val hops_theme_dark_onPrimaryContainer = Color(0xFFA7F5A6)
val hops_theme_dark_secondary = Color(0xFFB9CCB4)
val hops_theme_dark_onSecondary = Color(0xFF253424)
val hops_theme_dark_secondaryContainer = Color(0xFF3B4B39)
val hops_theme_dark_onSecondaryContainer = Color(0xFFD5E8CF)
val hops_theme_dark_tertiary = Color(0xFFA1CED5)
val hops_theme_dark_onTertiary = Color(0xFF00363C)
val hops_theme_dark_tertiaryContainer = Color(0xFF1F4D53)
val hops_theme_dark_onTertiaryContainer = Color(0xFFBCEBF1)
val hops_theme_dark_error = Color(0xFFFFB4AB)
val hops_theme_dark_errorContainer = Color(0xFF93000A)
val hops_theme_dark_onError = Color(0xFF690005)
val hops_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val hops_theme_dark_background = Color(0xFF1A1C19)
val hops_theme_dark_onBackground = Color(0xFFE2E3DD)
val hops_theme_dark_surface = Color(0xFF1A1C19)
val hops_theme_dark_onSurface = Color(0xFFE2E3DD)
val hops_theme_dark_surfaceVariant = Color(0xFF424940)
val hops_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val hops_theme_dark_outline = Color(0xFF8C9388)
val hops_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
val hops_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val hops_theme_dark_inversePrimary = Color(0xFF226C2D)
val hops_theme_dark_shadow = Color(0xFF000000)
val hops_theme_dark_surfaceTint = Color(0xFF8CD88C)
val hops_theme_dark_outlineVariant = Color(0xFF424940)
val hops_theme_dark_scrim = Color(0xFF000000)

val HopsLightColors = lightColorScheme(
    primary = hops_theme_light_primary,
    onPrimary = hops_theme_light_onPrimary,
    primaryContainer = hops_theme_light_primaryContainer,
    onPrimaryContainer = hops_theme_light_onPrimaryContainer,
    secondary = hops_theme_light_secondary,
    onSecondary = hops_theme_light_onSecondary,
    secondaryContainer = hops_theme_light_secondaryContainer,
    onSecondaryContainer = hops_theme_light_onSecondaryContainer,
    tertiary = hops_theme_light_tertiary,
    onTertiary = hops_theme_light_onTertiary,
    tertiaryContainer = hops_theme_light_tertiaryContainer,
    onTertiaryContainer = hops_theme_light_onTertiaryContainer,
    error = hops_theme_light_error,
    errorContainer = hops_theme_light_errorContainer,
    onError = hops_theme_light_onError,
    onErrorContainer = hops_theme_light_onErrorContainer,
    background = hops_theme_light_background,
    onBackground = hops_theme_light_onBackground,
    surface = hops_theme_light_surface,
    onSurface = hops_theme_light_onSurface,
    surfaceVariant = hops_theme_light_surfaceVariant,
    onSurfaceVariant = hops_theme_light_onSurfaceVariant,
    outline = hops_theme_light_outline,
    inverseOnSurface = hops_theme_light_inverseOnSurface,
    inverseSurface = hops_theme_light_inverseSurface,
    inversePrimary = hops_theme_light_inversePrimary,
    surfaceTint = hops_theme_light_surfaceTint,
    outlineVariant = hops_theme_light_outlineVariant,
    scrim = hops_theme_light_scrim
)

val HopsDarkColors = darkColorScheme(
    primary = hops_theme_dark_primary,
    onPrimary = hops_theme_dark_onPrimary,
    primaryContainer = hops_theme_dark_primaryContainer,
    onPrimaryContainer = hops_theme_dark_onPrimaryContainer,
    secondary = hops_theme_dark_secondary,
    onSecondary = hops_theme_dark_onSecondary,
    secondaryContainer = hops_theme_dark_secondaryContainer,
    onSecondaryContainer = hops_theme_dark_onSecondaryContainer,
    tertiary = hops_theme_dark_tertiary,
    onTertiary = hops_theme_dark_onTertiary,
    tertiaryContainer = hops_theme_dark_tertiaryContainer,
    onTertiaryContainer = hops_theme_dark_onTertiaryContainer,
    error = hops_theme_dark_error,
    errorContainer = hops_theme_dark_errorContainer,
    onError = hops_theme_dark_onError,
    onErrorContainer = hops_theme_dark_onErrorContainer,
    background = hops_theme_dark_background,
    onBackground = hops_theme_dark_onBackground,
    surface = hops_theme_dark_surface,
    onSurface = hops_theme_dark_onSurface,
    surfaceVariant = hops_theme_dark_surfaceVariant,
    onSurfaceVariant = hops_theme_dark_onSurfaceVariant,
    outline = hops_theme_dark_outline,
    inverseOnSurface = hops_theme_dark_inverseOnSurface,
    inverseSurface = hops_theme_dark_inverseSurface,
    inversePrimary = hops_theme_dark_inversePrimary,
    surfaceTint = hops_theme_dark_surfaceTint,
    outlineVariant = hops_theme_dark_outlineVariant,
    scrim = hops_theme_dark_scrim
)
