package com.fair.tool_belt_abv.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val lager_theme_light_primary = Color(0xFF785A00)
val lager_theme_light_onPrimary = Color(0xFFFFFFFF)
val lager_theme_light_primaryContainer = Color(0xFFFFDF9B)
val lager_theme_light_onPrimaryContainer = Color(0xFF251A00)
val lager_theme_light_secondary = Color(0xFF6B5D3F)
val lager_theme_light_onSecondary = Color(0xFFFFFFFF)
val lager_theme_light_secondaryContainer = Color(0xFFF4E0BB)
val lager_theme_light_onSecondaryContainer = Color(0xFF241A04)
val lager_theme_light_tertiary = Color(0xFF496547)
val lager_theme_light_onTertiary = Color(0xFFFFFFFF)
val lager_theme_light_tertiaryContainer = Color(0xFFCBEBC5)
val lager_theme_light_onTertiaryContainer = Color(0xFF062109)
val lager_theme_light_error = Color(0xFFBA1A1A)
val lager_theme_light_errorContainer = Color(0xFFFFDAD6)
val lager_theme_light_onError = Color(0xFFFFFFFF)
val lager_theme_light_onErrorContainer = Color(0xFF410002)
val lager_theme_light_background = Color(0xFFFFFBFF)
val lager_theme_light_onBackground = Color(0xFF1E1B16)
val lager_theme_light_surface = Color(0xFFFFFBFF)
val lager_theme_light_onSurface = Color(0xFF1E1B16)
val lager_theme_light_surfaceVariant = Color(0xFFEDE1CF)
val lager_theme_light_onSurfaceVariant = Color(0xFF4D4639)
val lager_theme_light_outline = Color(0xFF7F7667)
val lager_theme_light_inverseOnSurface = Color(0xFFF7F0E7)
val lager_theme_light_inverseSurface = Color(0xFF33302A)
val lager_theme_light_inversePrimary = Color(0xFFF2BF3F)
val lager_theme_light_shadow = Color(0xFF000000)
val lager_theme_light_surfaceTint = Color(0xFF785A00)
val lager_theme_light_outlineVariant = Color(0xFFD0C5B4)
val lager_theme_light_scrim = Color(0xFF000000)

val lager_theme_dark_primary = Color(0xFFF2BF3F)
val lager_theme_dark_onPrimary = Color(0xFF3F2E00)
val lager_theme_dark_primaryContainer = Color(0xFF5A4300)
val lager_theme_dark_onPrimaryContainer = Color(0xFFFFDF9B)
val lager_theme_dark_secondary = Color(0xFFD7C4A0)
val lager_theme_dark_onSecondary = Color(0xFF3A2F15)
val lager_theme_dark_secondaryContainer = Color(0xFF52452A)
val lager_theme_dark_onSecondaryContainer = Color(0xFFF4E0BB)
val lager_theme_dark_tertiary = Color(0xFFAFCFAA)
val lager_theme_dark_onTertiary = Color(0xFF1C361C)
val lager_theme_dark_tertiaryContainer = Color(0xFF324D31)
val lager_theme_dark_onTertiaryContainer = Color(0xFFCBEBC5)
val lager_theme_dark_error = Color(0xFFFFB4AB)
val lager_theme_dark_errorContainer = Color(0xFF93000A)
val lager_theme_dark_onError = Color(0xFF690005)
val lager_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val lager_theme_dark_background = Color(0xFF1E1B16)
val lager_theme_dark_onBackground = Color(0xFFE9E1D9)
val lager_theme_dark_surface = Color(0xFF1E1B16)
val lager_theme_dark_onSurface = Color(0xFFE9E1D9)
val lager_theme_dark_surfaceVariant = Color(0xFF4D4639)
val lager_theme_dark_onSurfaceVariant = Color(0xFFD0C5B4)
val lager_theme_dark_outline = Color(0xFF999080)
val lager_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val lager_theme_dark_inverseSurface = Color(0xFFE9E1D9)
val lager_theme_dark_inversePrimary = Color(0xFF785A00)
val lager_theme_dark_shadow = Color(0xFF000000)
val lager_theme_dark_surfaceTint = Color(0xFFF2BF3F)
val lager_theme_dark_outlineVariant = Color(0xFF4D4639)
val lager_theme_dark_scrim = Color(0xFF000000)

val LagerLightColors = lightColorScheme(
    primary = lager_theme_light_primary,
    onPrimary = lager_theme_light_onPrimary,
    primaryContainer = lager_theme_light_primaryContainer,
    onPrimaryContainer = lager_theme_light_onPrimaryContainer,
    secondary = lager_theme_light_secondary,
    onSecondary = lager_theme_light_onSecondary,
    secondaryContainer = lager_theme_light_secondaryContainer,
    onSecondaryContainer = lager_theme_light_onSecondaryContainer,
    tertiary = lager_theme_light_tertiary,
    onTertiary = lager_theme_light_onTertiary,
    tertiaryContainer = lager_theme_light_tertiaryContainer,
    onTertiaryContainer = lager_theme_light_onTertiaryContainer,
    error = lager_theme_light_error,
    errorContainer = lager_theme_light_errorContainer,
    onError = lager_theme_light_onError,
    onErrorContainer = lager_theme_light_onErrorContainer,
    background = lager_theme_light_background,
    onBackground = lager_theme_light_onBackground,
    surface = lager_theme_light_surface,
    onSurface = lager_theme_light_onSurface,
    surfaceVariant = lager_theme_light_surfaceVariant,
    onSurfaceVariant = lager_theme_light_onSurfaceVariant,
    outline = lager_theme_light_outline,
    inverseOnSurface = lager_theme_light_inverseOnSurface,
    inverseSurface = lager_theme_light_inverseSurface,
    inversePrimary = lager_theme_light_inversePrimary,
    surfaceTint = lager_theme_light_surfaceTint,
    outlineVariant = lager_theme_light_outlineVariant,
    scrim = lager_theme_light_scrim,
)

val LagerDarkColors = darkColorScheme(
    primary = lager_theme_dark_primary,
    onPrimary = lager_theme_dark_onPrimary,
    primaryContainer = lager_theme_dark_primaryContainer,
    onPrimaryContainer = lager_theme_dark_onPrimaryContainer,
    secondary = lager_theme_dark_secondary,
    onSecondary = lager_theme_dark_onSecondary,
    secondaryContainer = lager_theme_dark_secondaryContainer,
    onSecondaryContainer = lager_theme_dark_onSecondaryContainer,
    tertiary = lager_theme_dark_tertiary,
    onTertiary = lager_theme_dark_onTertiary,
    tertiaryContainer = lager_theme_dark_tertiaryContainer,
    onTertiaryContainer = lager_theme_dark_onTertiaryContainer,
    error = lager_theme_dark_error,
    errorContainer = lager_theme_dark_errorContainer,
    onError = lager_theme_dark_onError,
    onErrorContainer = lager_theme_dark_onErrorContainer,
    background = lager_theme_dark_background,
    onBackground = lager_theme_dark_onBackground,
    surface = lager_theme_dark_surface,
    onSurface = lager_theme_dark_onSurface,
    surfaceVariant = lager_theme_dark_surfaceVariant,
    onSurfaceVariant = lager_theme_dark_onSurfaceVariant,
    outline = lager_theme_dark_outline,
    inverseOnSurface = lager_theme_dark_inverseOnSurface,
    inverseSurface = lager_theme_dark_inverseSurface,
    inversePrimary = lager_theme_dark_inversePrimary,
    surfaceTint = lager_theme_dark_surfaceTint,
    outlineVariant = lager_theme_dark_outlineVariant,
    scrim = lager_theme_dark_scrim,
)