package com.example.compose
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val legacy_theme_light_primary = Color(0xFF005DB7)
val legacy_theme_light_onPrimary = Color(0xFFFFFFFF)
val legacy_theme_light_primaryContainer = Color(0xFFD6E3FF)
val legacy_theme_light_onPrimaryContainer = Color(0xFF001B3D)
val legacy_theme_light_secondary = Color(0xFF555F71)
val legacy_theme_light_onSecondary = Color(0xFFFFFFFF)
val legacy_theme_light_secondaryContainer = Color(0xFFD9E2F9)
val legacy_theme_light_onSecondaryContainer = Color(0xFF121C2B)
val legacy_theme_light_tertiary = Color(0xFF006685)
val legacy_theme_light_onTertiary = Color(0xFFFFFFFF)
val legacy_theme_light_tertiaryContainer = Color(0xFFBFE9FF)
val legacy_theme_light_onTertiaryContainer = Color(0xFF001F2A)
val legacy_theme_light_error = Color(0xFFBA1A1A)
val legacy_theme_light_errorContainer = Color(0xFFFFDAD6)
val legacy_theme_light_onError = Color(0xFFFFFFFF)
val legacy_theme_light_onErrorContainer = Color(0xFF410002)
val legacy_theme_light_background = Color(0xFFF8FDFF)
val legacy_theme_light_onBackground = Color(0xFF001F25)
val legacy_theme_light_surface = Color(0xFFF8FDFF)
val legacy_theme_light_onSurface = Color(0xFF001F25)
val legacy_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val legacy_theme_light_onSurfaceVariant = Color(0xFF44474E)
val legacy_theme_light_outline = Color(0xFF74777F)
val legacy_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val legacy_theme_light_inverseSurface = Color(0xFF00363F)
val legacy_theme_light_inversePrimary = Color(0xFFA9C7FF)
val legacy_theme_light_shadow = Color(0xFF000000)
val legacy_theme_light_surfaceTint = Color(0xFF005DB7)
val legacy_theme_light_outlineVariant = Color(0xFFC4C6CF)
val legacy_theme_light_scrim = Color(0xFF000000)

val legacy_theme_dark_primary = Color(0xFFA9C7FF)
val legacy_theme_dark_onPrimary = Color(0xFF003063)
val legacy_theme_dark_primaryContainer = Color(0xFF00468C)
val legacy_theme_dark_onPrimaryContainer = Color(0xFFD6E3FF)
val legacy_theme_dark_secondary = Color(0xFFBDC7DC)
val legacy_theme_dark_onSecondary = Color(0xFF283141)
val legacy_theme_dark_secondaryContainer = Color(0xFF3E4758)
val legacy_theme_dark_onSecondaryContainer = Color(0xFFD9E2F9)
val legacy_theme_dark_tertiary = Color(0xFF6DD2FF)
val legacy_theme_dark_onTertiary = Color(0xFF003547)
val legacy_theme_dark_tertiaryContainer = Color(0xFF004D65)
val legacy_theme_dark_onTertiaryContainer = Color(0xFFBFE9FF)
val legacy_theme_dark_error = Color(0xFFFFB4AB)
val legacy_theme_dark_errorContainer = Color(0xFF93000A)
val legacy_theme_dark_onError = Color(0xFF690005)
val legacy_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val legacy_theme_dark_background = Color(0xFF001F25)
val legacy_theme_dark_onBackground = Color(0xFFA6EEFF)
val legacy_theme_dark_surface = Color(0xFF001F25)
val legacy_theme_dark_onSurface = Color(0xFFA6EEFF)
val legacy_theme_dark_surfaceVariant = Color(0xFF44474E)
val legacy_theme_dark_onSurfaceVariant = Color(0xFFC4C6CF)
val legacy_theme_dark_outline = Color(0xFF8E9099)
val legacy_theme_dark_inverseOnSurface = Color(0xFF001F25)
val legacy_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val legacy_theme_dark_inversePrimary = Color(0xFF005DB7)
val legacy_theme_dark_shadow = Color(0xFF000000)
val legacy_theme_dark_surfaceTint = Color(0xFFA9C7FF)
val legacy_theme_dark_outlineVariant = Color(0xFF44474E)
val legacy_theme_dark_scrim = Color(0xFF000000)


val LightLegacyColors = lightColorScheme(
    primary = legacy_theme_light_primary,
    onPrimary = legacy_theme_light_onPrimary,
    primaryContainer = legacy_theme_light_primaryContainer,
    onPrimaryContainer = legacy_theme_light_onPrimaryContainer,
    secondary = legacy_theme_light_secondary,
    onSecondary = legacy_theme_light_onSecondary,
    secondaryContainer = legacy_theme_light_secondaryContainer,
    onSecondaryContainer = legacy_theme_light_onSecondaryContainer,
    tertiary = legacy_theme_light_tertiary,
    onTertiary = legacy_theme_light_onTertiary,
    tertiaryContainer = legacy_theme_light_tertiaryContainer,
    onTertiaryContainer = legacy_theme_light_onTertiaryContainer,
    error = legacy_theme_light_error,
    errorContainer = legacy_theme_light_errorContainer,
    onError = legacy_theme_light_onError,
    onErrorContainer = legacy_theme_light_onErrorContainer,
    background = legacy_theme_light_background,
    onBackground = legacy_theme_light_onBackground,
    surface = legacy_theme_light_surface,
    onSurface = legacy_theme_light_onSurface,
    surfaceVariant = legacy_theme_light_surfaceVariant,
    onSurfaceVariant = legacy_theme_light_onSurfaceVariant,
    outline = legacy_theme_light_outline,
    inverseOnSurface = legacy_theme_light_inverseOnSurface,
    inverseSurface = legacy_theme_light_inverseSurface,
    inversePrimary = legacy_theme_light_inversePrimary,
    surfaceTint = legacy_theme_light_surfaceTint,
    outlineVariant = legacy_theme_light_outlineVariant,
    scrim = legacy_theme_light_scrim,
)


val DarkLegacyColors = darkColorScheme(
    primary = legacy_theme_dark_primary,
    onPrimary = legacy_theme_dark_onPrimary,
    primaryContainer = legacy_theme_dark_primaryContainer,
    onPrimaryContainer = legacy_theme_dark_onPrimaryContainer,
    secondary = legacy_theme_dark_secondary,
    onSecondary = legacy_theme_dark_onSecondary,
    secondaryContainer = legacy_theme_dark_secondaryContainer,
    onSecondaryContainer = legacy_theme_dark_onSecondaryContainer,
    tertiary = legacy_theme_dark_tertiary,
    onTertiary = legacy_theme_dark_onTertiary,
    tertiaryContainer = legacy_theme_dark_tertiaryContainer,
    onTertiaryContainer = legacy_theme_dark_onTertiaryContainer,
    error = legacy_theme_dark_error,
    errorContainer = legacy_theme_dark_errorContainer,
    onError = legacy_theme_dark_onError,
    onErrorContainer = legacy_theme_dark_onErrorContainer,
    background = legacy_theme_dark_background,
    onBackground = legacy_theme_dark_onBackground,
    surface = legacy_theme_dark_surface,
    onSurface = legacy_theme_dark_onSurface,
    surfaceVariant = legacy_theme_dark_surfaceVariant,
    onSurfaceVariant = legacy_theme_dark_onSurfaceVariant,
    outline = legacy_theme_dark_outline,
    inverseOnSurface = legacy_theme_dark_inverseOnSurface,
    inverseSurface = legacy_theme_dark_inverseSurface,
    inversePrimary = legacy_theme_dark_inversePrimary,
    surfaceTint = legacy_theme_dark_surfaceTint,
    outlineVariant = legacy_theme_dark_outlineVariant,
    scrim = legacy_theme_dark_scrim,
)