package com.fair.tool_belt_abv.ui.theme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val stout_theme_light_primary = Color(0xFF9A4523)
val stout_theme_light_onPrimary = Color(0xFFFFFFFF)
val stout_theme_light_primaryContainer = Color(0xFFFFDBCF)
val stout_theme_light_onPrimaryContainer = Color(0xFF380D00)
val stout_theme_light_secondary = Color(0xFF77574C)
val stout_theme_light_onSecondary = Color(0xFFFFFFFF)
val stout_theme_light_secondaryContainer = Color(0xFFFFDBCF)
val stout_theme_light_onSecondaryContainer = Color(0xFF2C160D)
val stout_theme_light_tertiary = Color(0xFF695E2F)
val stout_theme_light_onTertiary = Color(0xFFFFFFFF)
val stout_theme_light_tertiaryContainer = Color(0xFFF2E2A8)
val stout_theme_light_onTertiaryContainer = Color(0xFF211B00)
val stout_theme_light_error = Color(0xFFBA1A1A)
val stout_theme_light_errorContainer = Color(0xFFFFDAD6)
val stout_theme_light_onError = Color(0xFFFFFFFF)
val stout_theme_light_onErrorContainer = Color(0xFF410002)
val stout_theme_light_background = Color(0xFFFFFBFF)
val stout_theme_light_onBackground = Color(0xFF201A18)
val stout_theme_light_surface = Color(0xFFFFFBFF)
val stout_theme_light_onSurface = Color(0xFF201A18)
val stout_theme_light_surfaceVariant = Color(0xFFF5DED6)
val stout_theme_light_onSurfaceVariant = Color(0xFF53433E)
val stout_theme_light_outline = Color(0xFF85736D)
val stout_theme_light_inverseOnSurface = Color(0xFFFBEEEA)
val stout_theme_light_inverseSurface = Color(0xFF362F2C)
val stout_theme_light_inversePrimary = Color(0xFFFFB59B)
val stout_theme_light_surfaceTint = Color(0xFF9A4523)
val stout_theme_light_outlineVariant = Color(0xFFD8C2BB)
val stout_theme_light_scrim = Color(0xFF000000)

val stout_theme_dark_primary = Color(0xFFFFB59B)
val stout_theme_dark_onPrimary = Color(0xFF5B1B00)
val stout_theme_dark_primaryContainer = Color(0xFF7B2E0D)
val stout_theme_dark_onPrimaryContainer = Color(0xFFFFDBCF)
val stout_theme_dark_secondary = Color(0xFFE7BEAF)
val stout_theme_dark_onSecondary = Color(0xFF442A21)
val stout_theme_dark_secondaryContainer = Color(0xFF5D4035)
val stout_theme_dark_onSecondaryContainer = Color(0xFFFFDBCF)
val stout_theme_dark_tertiary = Color(0xFFD5C68E)
val stout_theme_dark_onTertiary = Color(0xFF393005)
val stout_theme_dark_tertiaryContainer = Color(0xFF50471A)
val stout_theme_dark_onTertiaryContainer = Color(0xFFF2E2A8)
val stout_theme_dark_error = Color(0xFFFFB4AB)
val stout_theme_dark_errorContainer = Color(0xFF93000A)
val stout_theme_dark_onError = Color(0xFF690005)
val stout_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val stout_theme_dark_background = Color(0xFF201A18)
val stout_theme_dark_onBackground = Color(0xFFEDE0DC)
val stout_theme_dark_surface = Color(0xFF201A18)
val stout_theme_dark_onSurface = Color(0xFFEDE0DC)
val stout_theme_dark_surfaceVariant = Color(0xFF53433E)
val stout_theme_dark_onSurfaceVariant = Color(0xFFD8C2BB)
val stout_theme_dark_outline = Color(0xFFA08D86)
val stout_theme_dark_inverseOnSurface = Color(0xFF201A18)
val stout_theme_dark_inverseSurface = Color(0xFFEDE0DC)
val stout_theme_dark_inversePrimary = Color(0xFF9A4523)
val stout_theme_dark_surfaceTint = Color(0xFFFFB59B)
val stout_theme_dark_outlineVariant = Color(0xFF53433E)
val stout_theme_dark_scrim = Color(0xFF000000)

val StoutLightColors = lightColorScheme(
    primary = stout_theme_light_primary,
    onPrimary = stout_theme_light_onPrimary,
    primaryContainer = stout_theme_light_primaryContainer,
    onPrimaryContainer = stout_theme_light_onPrimaryContainer,
    secondary = stout_theme_light_secondary,
    onSecondary = stout_theme_light_onSecondary,
    secondaryContainer = stout_theme_light_secondaryContainer,
    onSecondaryContainer = stout_theme_light_onSecondaryContainer,
    tertiary = stout_theme_light_tertiary,
    onTertiary = stout_theme_light_onTertiary,
    tertiaryContainer = stout_theme_light_tertiaryContainer,
    onTertiaryContainer = stout_theme_light_onTertiaryContainer,
    error = stout_theme_light_error,
    errorContainer = stout_theme_light_errorContainer,
    onError = stout_theme_light_onError,
    onErrorContainer = stout_theme_light_onErrorContainer,
    background = stout_theme_light_background,
    onBackground = stout_theme_light_onBackground,
    surface = stout_theme_light_surface,
    onSurface = stout_theme_light_onSurface,
    surfaceVariant = stout_theme_light_surfaceVariant,
    onSurfaceVariant = stout_theme_light_onSurfaceVariant,
    outline = stout_theme_light_outline,
    inverseOnSurface = stout_theme_light_inverseOnSurface,
    inverseSurface = stout_theme_light_inverseSurface,
    inversePrimary = stout_theme_light_inversePrimary,
    surfaceTint = stout_theme_light_surfaceTint,
    outlineVariant = stout_theme_light_outlineVariant,
    scrim = stout_theme_light_scrim
)

val StoutDarkColors = darkColorScheme(
    primary = stout_theme_dark_primary,
    onPrimary = stout_theme_dark_onPrimary,
    primaryContainer = stout_theme_dark_primaryContainer,
    onPrimaryContainer = stout_theme_dark_onPrimaryContainer,
    secondary = stout_theme_dark_secondary,
    onSecondary = stout_theme_dark_onSecondary,
    secondaryContainer = stout_theme_dark_secondaryContainer,
    onSecondaryContainer = stout_theme_dark_onSecondaryContainer,
    tertiary = stout_theme_dark_tertiary,
    onTertiary = stout_theme_dark_onTertiary,
    tertiaryContainer = stout_theme_dark_tertiaryContainer,
    onTertiaryContainer = stout_theme_dark_onTertiaryContainer,
    error = stout_theme_dark_error,
    errorContainer = stout_theme_dark_errorContainer,
    onError = stout_theme_dark_onError,
    onErrorContainer = stout_theme_dark_onErrorContainer,
    background = stout_theme_dark_background,
    onBackground = stout_theme_dark_onBackground,
    surface = stout_theme_dark_surface,
    onSurface = stout_theme_dark_onSurface,
    surfaceVariant = stout_theme_dark_surfaceVariant,
    onSurfaceVariant = stout_theme_dark_onSurfaceVariant,
    outline = stout_theme_dark_outline,
    inverseOnSurface = stout_theme_dark_inverseOnSurface,
    inverseSurface = stout_theme_dark_inverseSurface,
    inversePrimary = stout_theme_dark_inversePrimary,
    surfaceTint = stout_theme_dark_surfaceTint,
    outlineVariant = stout_theme_dark_outlineVariant,
    scrim = stout_theme_dark_scrim
)
